# -*- coding: utf-8 -*-
"""Program PI_50422581_Firda Humaira.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17tRupC-yuc3mdds63ls6qEZq3s_G7g4L

# **IMPORT LIBRARY**
"""

# Install
!pip install google-play-scraper
!pip install optuna
!pip install sastrawi

# General
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import csv
import re
import string
import requests
import optuna
from io import StringIO
from google_play_scraper import app, reviews, Sort # Mengambil data aplikasi dan ulasan

# Pengaturan umum
pd.options.mode.chained_assignment = None
seed = 0
np.random.seed(seed)

# Preprocessing
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt_tab')   # untuk word_tokenize
nltk.download('stopwords')   # untuk stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# Feature Extraction
from sklearn.feature_extraction.text import TfidfVectorizer

# Model Training & Evaluation
from sklearn.svm import SVC
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from collections import Counter
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, precision_score
from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score

# Visualization
from wordcloud import WordCloud
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

"""# **SCRAPPING DATA**"""

# Ambil semua ulasan dari aplikasi dengan ID tertentu
scrapreview, continuation_token = reviews(
    'com.bca.mybca.omni.android',  # ID aplikasi
    lang='id',                     # Bahasa ulasan
    country='id',                  # Negara asal ulasan
    sort=Sort.MOST_RELEVANT,       # Urutan ulasan
    count=10000                    # Maks jumlah ulasan
)

# Menyimpan ke CSV
with open('ulasan_sentimen.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.writer(file)
    writer.writerow(['Review'])  # Menulis header kolom
    for review in scrapreview:
        writer.writerow([review['content']])  # Menulis konten ulasan ke dalam file CSV

df = pd.DataFrame(scrapreview)
df.shape
df.head()
df.to_csv('ulasan_sentimen.csv', index=False)

df

"""# **CLEANING DATA**"""

df = pd.DataFrame(scrapreview)

# Jumlah baris dan kolom
jumlah_ulasan, jumlah_kolom = df.shape
print("Jumlah ulasan yang berhasil diambil:", jumlah_ulasan)
print("Jumlah kolom dalam DataFrame:", jumlah_kolom)

df.head()

df.info()

# Cek Missing Values
print(df.isnull().sum())

# Mengecek jumlah data duplikat
print(df.duplicated().sum())

clean_df = df.copy()

# Hapus kolom yang tidak diinginkan
clean_df = clean_df.drop(columns= [
    'reviewId', 'userName', 'userImage', 'thumbsUpCount', 'score',
    'reviewCreatedVersion', 'replyContent', 'repliedAt', 'appVersion', 'at'
    ])

clean_df

# mendownload hasil cleaning dalam file csv
from google.colab import files

clean_df.to_csv('Data_clean.csv',index=False)

files.download('Data_clean.csv')

print("file ulasan sudah berhasil didownload!")

clean_df.info()

"""# **PREPROCESSING**"""

# pola emoji & simbol non‑ASCII umum
EMOJI_PATTERN = re.compile(
    "["
    "\U0001F600-\U0001F64F"  # emotikon
    "\U0001F300-\U0001F5FF"  # simbol & pictograph
    "\U0001F680-\U0001F6FF"  # transport & map
    "\U0001F1E0-\U0001F1FF"  # bendera
    "\U00002702-\U000027B0"  # dingbats
    "\U000024C2-\U0001F251"
    "]+",
    flags=re.UNICODE,
)

# Menghapus elemen-elemen tidak penting dari teks
def cleaningText(text: str) -> str:
    text = re.sub(r'@[A-Za-z0-9_]+',  '', text)      # mention
    text = re.sub(r'#[A-Za-z0-9_]+',  '', text)      # hashtag
    text = re.sub(r'RT\b',              '', text)    # RT
    text = re.sub(r'http\S+',           '', text)    # link
    text = re.sub(r'[0-9]+',            '', text)    # angka
    text = EMOJI_PATTERN.sub(' ', text)              # 🚫 emoji
    text = re.sub(r'[^\w\s]', '', text)
    text = text.replace('\n', ' ')
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = text.strip()
    return text

# Mengubah semua huruf menjadi huruf kecil
def casefoldingText(text):
    return text.lower()

# Memecah kalimat menjadi token (kata-kata)
def tokenizingText(text):
    return word_tokenize(text)

# Menghapus kata-kata umum (stopwords)
def filteringText(text):
    listStopwords = set(stopwords.words('indonesian'))
    listStopwords1 = set(stopwords.words('english'))
    listStopwords.update(listStopwords1)
    listStopwords.update([
        'dan', 'atau', 'tetapi', 'tapi', 'lalu', 'kemudian', 'di', 'ke', 'dari', 'untuk',
        'pada', 'dengan', 'saya', 'kamu', 'dia', 'mereka', 'kita', 'ini', 'itu', 'adalah',
        'telah', 'akan', 'sedang', 'apa', 'siapa', 'mengapa', 'bagaimana', 'tidak', 'ya',
        'saja', 'aja', 'bahkan', 'namun', 'karena'
    ])
    filtered = []
    for txt in text:
        if txt not in listStopwords:
            filtered.append(txt)
    text = filtered
    return text


# Melakukan stemming (mengembalikan kata ke bentuk dasar)
def stemmingText(text):
    factory = StemmerFactory()
    stemmer = factory.create_stemmer()

    words = text.split()
    stemmed = [stemmer.stem(word) for word in words]
    return ' '.join(stemmed)

# Menggabungkan daftar kata menjadi kalimat
def toSentence(list_words):
     return ' '.join(list_words)

slangwords = {
    "ga": "tidak", "gk": "tidak", "gak": "tidak", "otp": "kode verifikasi", "bsa": "bisa",
    "gamasuk": "tidak masuk", "udah": "sudah", "udh": "sudah", "tp": "tapi", "trs": "terus",
    "ribet": "rumit", "fix": "perbaikan", "ampas": "tidak berguna", "mahal dikit": "sedikit mahal",
    "tdk": "tidak", "tp": "tetapi", "tapi": "tetapi", "dgn": "dengan", "apl": "aplikasi",
    "fine²": "baik-baik saja", "muncul²": "muncul-muncul", "bug": "masalah teknis", "hrs": "harus",
    "lancar": "berjalan baik", "dikit": "sedikit", "cba": "coba", "tetep": "tetap", "kyk": "seperti",
    "emg": "memang", "bgt": "sangat", "banget": "sangat", "kok": "kenapa", "lemot": "lambat",
    "tf": "transfer", "smua": "semua", "jd": "jadi", "pake": "gunakan", "pakai": "gunakan",
    "cm": "cuma", "adapalah": "ada saja", "gimna": "bagaimana", "blm": "belum", "skrg": "sekarang",
    "dr": "dari", "klo": "kalau", "klw": "kalau", "karna": "karena", "yg": "yang", "dlu": "dulu",
    "bener": "benar", "nih": "ini", "aja": "saja", "kayak": "seperti", "gitu": "begitu", "kan": "bukan",
    "bikin": "buat", "capek": "lelah", "bosen": "bosan", "nomer": "nomor", "hp": "ponsel",
    "cs": "layanan pelanggan", "otomatis": "automatis", "gbsa": "tidak bisa", "gimana": "bagaimana",
    "wkwk": "tertawa", "hadeh": "mengeluh", "e-ktp": "KTP elektronik", "mutasi": "riwayat transaksi",
    "top up": "isi saldo", "vc": "video call", "paswod": "password", "tepasang": "terpasang",
    "sadonya": "saldonya", "sampe": "sampai", "kebuka": "terbuka", "kebanyakan": "terlalu banyak"
}

def fix_slangwords(text):
    words = text.split()
    fixed_words = []

    for word in words:
        # Remove punctuation for better matching
        clean_word = word.lower().strip('.,!?;:"\'')
        if clean_word in slangwords:
            replacement = slangwords[clean_word]
            # Preserve original capitalization
            if word[0].isupper():
                replacement = replacement.capitalize()
            fixed_words.append(replacement)
        else:
            fixed_words.append(word)

    fixed_text = ' '.join(fixed_words)
    return fixed_text

!pip install tqdm

from tqdm.notebook import tqdm
tqdm.pandas()

clean_df['text_clean'] = clean_df['content'].apply(cleaningText)
clean_df['text_casefoldingText'] = clean_df['text_clean'].apply(casefoldingText)
clean_df['text_slangwords'] = clean_df['text_casefoldingText'].apply(fix_slangwords)
clean_df['text_tokenizingText'] = clean_df['text_slangwords'].apply(tokenizingText)
clean_df['text_stopword'] = clean_df['text_tokenizingText'].apply(filteringText)
clean_df['text_stemming'] = clean_df['text_stopword'].progress_apply(lambda tokens: stemmingText(' '.join(tokens)).split())
clean_df['text_akhir'] = clean_df['text_stemming'].apply(lambda words: ' '.join(words))

clean_df

clean_df.to_csv('processing.csv', index=False)

"""# **LABELLING**"""

# Muat kamus kata positif dari GitHub
import requests, csv
from io import StringIO

lexicon_positive = dict()
resp = requests.get('https://raw.githubusercontent.com/firdahum/pi/main/lexicon_positive.csv')
if resp.status_code == 200:
    reader = csv.reader(StringIO(resp.text), delimiter=',')
    for row in reader:
        lexicon_positive[row[0]] = int(row[1])
else:
    print("Failed to fetch positive lexicon data")

# Muat kamus kata negatif dari GitHub
lexicon_negative = dict()
resp = requests.get('https://raw.githubusercontent.com/firdahum/pi/main/lexicon_negative.csv')
if resp.status_code == 200:
    reader = csv.reader(StringIO(resp.text), delimiter=',')
    for row in reader:
        lexicon_negative[row[0]] = int(row[1])
else:
    print("Failed to fetch negative lexicon data")

def lexicon(text):
    score = 0
    for word in text:
        if word in lexicon_positive:
            score += lexicon_positive[word]  # tambah skor jika positif

    for word in text:
        if word in lexicon_negative:
            score += lexicon_negative[word]  # kurangi skor jika negatif

    # positif jika skor > 0, negatif jika skor < 0, netral jika skor == 0
    if score > 0:
        polarity = 'positive'
    elif score < 0:
        polarity = 'negative'
    else:
        polarity = 'neutral'

    return score, polarity

# Menerapkan fungsi analisis sentimen pada data teks yang telah dibersihkan
results = clean_df['text_stopword'].apply(lexicon)

# Memisahkan hasil analisis menjadi dua kolom: skor dan label polaritas
results = list(zip(*results))
clean_df['polarity_score'] = results[0]
clean_df['polarity'] = results[1]

# Menampilkan jumlah masing-masing kategori polaritas
print(clean_df['polarity'].value_counts())

def analyzetweets(clean_df):
    pd.set_option('display.max_colwidth', 3000)

    # Positive Tweets
    positive_tweets = clean_df[clean_df['polarity'] == 'positive']
    positive_tweets = positive_tweets[['text_akhir', 'polarity_score', 'polarity','text_stopword']]
    positive_tweets = positive_tweets.sort_values(by='polarity_score', ascending=False).reset_index(drop=True)
    positive_tweets.index += 1

    # Negative Tweets
    negative_tweets = clean_df[clean_df['polarity'] == 'negative']
    negative_tweets = negative_tweets[['text_akhir', 'polarity_score', 'polarity','text_stopword']]
    negative_tweets = negative_tweets.sort_values(by='polarity_score', ascending=True).head(10).reset_index(drop=True)
    negative_tweets.index += 1

    # Neutral Tweets
    neutral_tweets = clean_df[clean_df['polarity'] == 'neutral']
    neutral_tweets = neutral_tweets[['text_akhir', 'polarity_score', 'polarity','text_stopword']]
    neutral_tweets = neutral_tweets.sort_values(by='polarity_score', ascending=False).reset_index(drop=True)
    neutral_tweets.index += 1

    # Word Cloud
    list_words = ''
    for tweet in clean_df['text_stopword']:
        for word in tweet:
            list_words += ' ' + word

    wordcloud = WordCloud(width=600, height=400, background_color='white', min_font_size=10).generate(list_words)

    fig, ax = plt.subplots(figsize=(8, 6))
    ax.set_title('Word Cloud of Tweets Data', fontsize=18)
    ax.grid(False)
    ax.imshow(wordcloud)
    fig.tight_layout(pad=0)
    ax.axis('off')
    plt.show()

    return positive_tweets, negative_tweets, neutral_tweets

positive_tweets, negative_tweets, neutral_tweets = analyzetweets(clean_df)

# Kumpulkan semua kata dari tweet negatif
list_words = ''
for tweet in negative_tweets['text_stopword']:
    for word in tweet:
        list_words += ' ' + word

# Buat WordCloud dari kata-kata yang terkumpul
wordcloud = WordCloud(width=500, height=300, background_color='white', min_font_size=10).generate(list_words)

# Tampilkan WordCloud
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title('Word Cloud of Negative Tweets Data', fontsize=18)
ax.grid(False)
ax.imshow(wordcloud)
fig.tight_layout(pad=0)
ax.axis('off')
plt.show()

# Kumpulkan semua kata dari tweet positif
list_words = ''
for tweet in positive_tweets['text_stopword']:
    for word in tweet:
        list_words += ' ' + word

# Buat dan tampilkan WordCloud
wordcloud = WordCloud(width=500, height=300, background_color='white', min_font_size=10).generate(list_words)
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title('Word Cloud of Positive Tweets Data', fontsize=18)
ax.grid(False)
ax.imshow(wordcloud)
fig.tight_layout(pad=0)
ax.axis('off')
plt.show()

# Kumpulkan semua kata dari tweet netral
list_words = ''
for tweet in neutral_tweets['text_stopword']:
    for word in tweet:
        list_words += ' ' + word

# Buat dan tampilkan WordCloud
wordcloud = WordCloud(width=500, height=300, background_color='white', min_font_size=10).generate(list_words)
fig, ax = plt.subplots(figsize=(8, 6))
ax.set_title('Word Cloud of Neutral Tweets Data', fontsize=18)
ax.grid(False)
ax.imshow(wordcloud)
fig.tight_layout(pad=0)
ax.axis('off')
plt.show()

# Visualisasi Distribusi Kelas Sentimen
plt.figure(figsize=(10, 6))
class_dist_plot = sns.countplot(x='polarity', data=clean_df)
plt.title('Class Distribution')

# Menampilkan jumlah pada masing-masing bar
for p in class_dist_plot.patches:
    class_dist_plot.annotate(format(p.get_height(), '.0f'),
                             (p.get_x() + p.get_width() / 2., p.get_height()),
                             ha='center', va='center',
                             xytext=(0, 10),
                             textcoords='offset points')
plt.show()

# Visualisasi Panjang Teks Review
plt.figure(figsize=(10, 6))
clean_df['text_length'] = clean_df['text_akhir'].apply(lambda x: len(x.split()))
sns.histplot(clean_df['text_length'])
plt.title('Text Length Distribution')
plt.show()

# Visualisasi Kata yang Paling Sering Muncul
plt.figure(figsize=(12, 6))
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(clean_df['text_akhir'])
tfidf_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df = tfidf_df.sum().reset_index(name='jumlah')
tfidf_df = tfidf_df.sort_values('jumlah', ascending=False).head(20)
sns.barplot(x='jumlah', y='index', data=tfidf_df)
plt.title('Most Frequent Words')
plt.show()

clean_df.head(2)

"""### TF-IDF"""

def prepare_features(clean_df):
    # Pisahkan data menjadi fitur dan label
    X = clean_df['text_akhir']
    y = clean_df['polarity']

    # Ekstraksi fitur TF-IDF
    tfidf = TfidfVectorizer(max_features=200, min_df=17, max_df=0.8)
    X_tfidf = tfidf.fit_transform(X)

    # Buat dataframe dari hasil ekstraksi
    features_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())

"""# **MODELLING**

## **DATA SPLITTING**
"""

def prepare_features(clean_df):
    # Pisahkan data menjadi fitur dan label
    X = clean_df['text_akhir']
    y = clean_df['polarity']

    # Ekstraksi fitur TF-IDF
    tfidf = TfidfVectorizer(max_features=200, min_df=17, max_df=0.8)
    X_tfidf = tfidf.fit_transform(X)

    # Buat dataframe dari hasil ekstraksi
    features_df = pd.DataFrame(X_tfidf.toarray(), columns=tfidf.get_feature_names_out())

    # Split data ke training dan testing
    X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.2, random_state=42)

    return X, y, tfidf, X_tfidf, features_df, X_train, X_test, y_train, y_test

X, y, tfidf, X_tfidf, features_df, X_train, X_test, y_train, y_test = prepare_features(clean_df)

features_df.head()

"""## **OVERSAMPLING**"""

# Hitung distribusi kelas sebelum SMOTE
before_counts = y_train.value_counts()

# Terapkan SMOTE ke data latih
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

# Hitung distribusi kelas sesudah SMOTE
after_counts = pd.Series(y_train_sm).value_counts()

# Buat pie chart
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Pie chart sebelum SMOTE
axes[0].pie(before_counts, labels=before_counts.index, autopct='%1.1f%%', startangle=90)
axes[0].set_title('Distribusi Kelas Sebelum SMOTE')

# Pie chart sesudah SMOTE
axes[1].pie(after_counts, labels=after_counts.index, autopct='%1.1f%%', startangle=90)
axes[1].set_title('Distribusi Kelas Sesudah SMOTE')

plt.tight_layout()
plt.show()

pd.DataFrame({
    "Sebelum SMOTE": before_counts,
    "Sesudah SMOTE": after_counts
})

"""# **SVM**"""

def objective(trial):
    # Suggest hyperparameters
    C = trial.suggest_float('C', 0.1, 30, log=True)
    gamma = trial.suggest_float('gamma', 1e-4, 1.0, log=True)

    model_svm = SVC(C=C, gamma=gamma, kernel='rbf')

    # Fit pada data train
    model_svm.fit(X_train.toarray(), y_train)

    # Prediksi dan hitung akurasi
    y_pred = model_svm.predict(X_test.toarray())
    return accuracy_score(y_test, y_pred)

# Buat study baru
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=30)  # Kamu bisa naikkan n_trials jika ingin hasil lebih optimal

# Tampilkan hasil terbaik
print("Best Parameters:", study.best_params)
print(f"Best Accuracy: {study.best_value * 100:.2f}%")

# --- Train ulang model_svm terbaik ---
best_svc = SVC(**study.best_params, kernel='rbf')
best_svc.fit(X_train.toarray(), y_train)

# Prediksi dan evaluasi
y_pred_test_svm = best_svc.predict(X_test.toarray())
y_pred_train_svm = best_svc.predict(X_train.toarray())

print(f"Akurasi Training: {accuracy_score(y_train, y_pred_train_svm) * 100:.2f}%")
print(f"Akurasi testing: {accuracy_score(y_test, y_pred_test_svm) * 100:.2f}%")

"""# **Decision Tree**"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Buat model_dt dengan default parameter
model_dt = DecisionTreeClassifier(random_state=42)

# Training
model_dt.fit(X_train, y_train)

# Prediksi
y_pred_train_dt = model_dt.predict(X_train)
y_pred_test_dt = model_dt.predict(X_test)

# Evaluasi akurasi
print(f"Akurasi Data Training: {accuracy_score(y_train, y_pred_train_dt) * 100:.2f}%")
print(f"Akurasi Data Testing: {accuracy_score(y_test, y_pred_test_dt) * 100:.2f}%")

"""# **Random Forest**"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Buat model_rf Random Forest dengan parameter default
model_rf = RandomForestClassifier(random_state=42)

# Training
model_rf.fit(X_train, y_train)

# Prediksi
y_pred_train_rf = model_rf.predict(X_train)
y_pred_test_rf = model_rf.predict(X_test)

# Evaluasi akurasi
print(f"Akurasi Data Training: {accuracy_score(y_train, y_pred_train_rf) * 100:.2f}%")
print(f"Akurasi Data Testing: {accuracy_score(y_test, y_pred_test_rf) * 100:.2f}%")

"""# **EVALUASI MODEL**"""

def evaluate_model(model, X, y_true, title="Evaluation"):
    # Prediksi
    y_pred = model.predict(X)

    # Confusion Matrix
    cm = confusion_matrix(y_true, y_pred)
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=model.classes_)
    disp.plot(cmap=plt.cm.Blues)
    plt.title(f"Confusion Matrix - {title}")
    plt.show()

    # Evaluation metrics
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted', zero_division=0)
    recall = recall_score(y_true, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_true, y_pred, average='weighted', zero_division=0)

    print(f"==Evaluation Report==")
    print(f"Accuracy : {accuracy * 100:.2f}%")
    print(f"Precision: {precision * 100:.2f}%")
    print(f"Recall   : {recall * 100:.2f}%")
    print(f"F1 Score : {f1 * 100:.2f}%")
    print("\n")
    print("\n            === Classification Report ===")
    print("\n")
    print(classification_report(y_true, y_pred, zero_division=0))

evaluate_model(best_svc, X_test.toarray(), y_test)

def evaluate_model(model_name, y_true, y_pred):

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(5, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f"Confusion Matrix - {model_name}")
    plt.xlabel("Predicted Label")
    plt.ylabel("True Label")
    plt.tight_layout()
    plt.show()

    print("Classification Report:")
    print(classification_report(y_true, y_pred))

evaluate_model("SVM", y_test, y_pred_test_svm)
evaluate_model("Decision Tree", y_test, y_pred_test_dt)
evaluate_model("Random Forest", y_test, y_pred_test_rf)

"""# **Inference**"""

sentimen_map = {
    'positive': 'POSITIF',
    'negative': 'NEGATIF',
    'neutral': 'NETRAL'
}

for i in range(3):
    kalimat_baru = input(f"[{i+1}/3] Masukkan kalimat: ")

    # Transform dan prediksi
    X_baru = tfidf.transform([kalimat_baru])
    hasil_prediksi = best_svc.predict(X_baru.toarray())

    print(f"Sentimen kalimat tersebut adalah: {sentimen_map[hasil_prediksi[0]]}\n")